apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: azure-ip-masq-agent
  namespace: kube-system
  labels:
    component: azure-ip-masq-agent
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    tier: node
spec:
  template:
    metadata:
      labels:
        k8s-app: azure-ip-masq-agent
        tier: node
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: azure-ip-masq-agent
        image: gcr.io/google-containers/ip-masq-agent-amd64:v2.0.0
        securityContext:
          privileged: true
        volumeMounts:
          - name: azure-ip-masq-agent-config-volume
            mountPath: /etc/config
        resources:
          requests:
            cpu: <kubernetesIPMasqAgentCPURequests>
            memory: <kubernetesIPMasqAgentMemoryRequests>
          limits:
            cpu: <kubernetesIPMasqAgentCPULimit>
            memory: <kubernetesIPMasqAgentMemoryLimit>
      volumes:
        - name: azure-ip-masq-agent-config-volume
          configMap:
            name: azure-ip-masq-agent-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-ip-masq-agent-config
  namespace: kube-system
  labels:
    component: azure-ip-masq-agent
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  ip-masq-agent: |-
    nonMasqueradeCIDRs:
      - <kubernetesNonMasqueradeCidr>
      - <azureCNINonMasqueradeIP>
    masqLinkLocal: <masqLinkLocalValue>
    resyncInterval: 60s