apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-connector
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: aci-connector
  labels:
    app: aci-connector
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: "EnsureExists"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - services
  - endpoints
  - events
  - secrets
  - nodes
  - nodes/status
  - pods/status
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: aci-connector
  labels:
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: aci-connector
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-connector
  namespace: kube-system
  labels:
    app: aci-connector
    name: aci-connector
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aci-connector
    spec:
      serviceAccountName: aci-connector
      containers:
      - name: aci-connector
        image: <kubernetesACIConnectorSpec>
        env:
        - name: AZURE_CLIENT_ID
          value: <kubernetesACIConnectorClientId>
        - name: AZURE_CLIENT_KEY
          value: <kubernetesACIConnectorClientKey>
        - name: AZURE_TENANT_ID
          value: <kubernetesACIConnectorTenantId>
        - name: AZURE_SUBSCRIPTION_ID
          value: <kubernetesACIConnectorSubscriptionId>
        - name: ACI_RESOURCE_GROUP
          value: <kubernetesACIConnectorResourceGroup>
        - name: ACI_REGION
          value: <kubernetesACIConnectorRegion>
        resources:
          requests:
            cpu: <kubernetesACIConnectorCPURequests>
            memory: <kubernetesACIConnectorMemoryRequests>
          limits:
            cpu: <kubernetesACIConnectorCPULimit>
            memory: <kubernetesACIConnectorMemoryLimit>
      nodeSelector:
        beta.kubernetes.io/os: linux
