#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  labels:
#    k8s-app: kube-addon-manager
#  name: kube-addon-manager
#  namespace: kube-system
#---
#apiVersion: rbac.authorization.k8s.io/v1beta1
#kind: ClusterRoleBinding
#metadata:
#  name: kube-addon-manager
#  labels:
#    k8s-app: kube-addon-manager
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: cluster-admin
#subjects:
#- kind: ServiceAccount
#  name: kube-addon-manager
#  namespace: kube-system
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    image: <kubernetesAddonManagerSpec>
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
    volumeMounts:
    - name: addons
      mountPath: "/etc/kubernetes/addons"
      readOnly: true
  serviceAccountName: kube-addon-manager
  volumes:
  - name: addons
    hostPath:
      path: "/etc/kubernetes/addons"