apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rescheduler-v0.3.0
  namespace: kube-system
  labels:
    k8s-app: rescheduler
    version: v0.3.0
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Rescheduler"
    addonmanager.kubernetes.io/mode: "Reconcile"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rescheduler
  template:
    metadata:
      labels:
        k8s-app: rescheduler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - image: <kubernetesReschedulerSpec>
        name: rescheduler
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        command:
        - sh
        - -c
        - '/rescheduler 2>&1'
        volumeMounts:
        - mountPath: /var/log/rescheduler.log
          name: logfile
          readOnly: false
        # TODO: Make resource requirements depend on the size of the cluster
      volumes:
      - hostPath:
          path: /var/log/rescheduler.log
        name: logfile