apiVersion: "v1"
kind: "Pod"
metadata:
  name: "kube-scheduler"
  namespace: "kube-system"
  labels:
    tier: control-plane
    component: kube-scheduler
spec:
  hostNetwork: true
  containers:
    - name: "kube-scheduler"
      image: "<kubernetesHyperkubeSpec>"
      command:
        - "/hyperkube"
        - "scheduler"
        - "--kubeconfig=/var/lib/kubelet/kubeconfig"
        - "--leader-elect=true"
        - "--v=2"
      volumeMounts:
        - name: "etc-kubernetes"
          mountPath: "/etc/kubernetes"
        - name: "var-lib-kubelet"
          mountPath: "/var/lib/kubelet"
  volumes:
    - name: "etc-kubernetes"
      hostPath:
        path: "/etc/kubernetes"
    - name: "var-lib-kubelet"
      hostPath:
        path: "/var/lib/kubelet"
        
