apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiller-deploy
  namespace: kube-system
  labels:
    app: helm
    name: tiller
    kubernetes.io/cluster-service: "true"
spec:
  template:
    labels:
      app: helm
      name: tiller
    spec:
      containers:
        env:
        - name: TILLER_NAMESPACE
          value: kube-system
        image: <kubernetesTillerSpec>
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
      nodeSelector:
        beta.kubernetes.io/os: linux
