# trigger:
# - master

# steps: 
# - create an VHD in Packer to normal storage account
# - copy from Packer storage account to classic storage account using AzCopy
# - generate SAS link from azure CLI
# - POST a new SKU to azure marketplace

phases:
- phase: build_vhd
  queue: Hosted Linux Preview
  steps:
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/acs-engine \
      -w /go/src/github.com/Azure/acs-engine \
      -e CLIENT_ID=${CLIENT_ID} \
      -e CLIENT_SECRET="$(CLIENT_SECRET)" \
      -e TENANT_ID=${TENANT_ID} \
      -e AZURE_VM_SIZE=${AZURE_VM_SIZE} \
      -e AZURE_RESOURCE_GROUP_NAME=${AZURE_RESOURCE_GROUP_NAME} \
      -e AZURE_LOCATION=${AZURE_LOCATION} \
      ${DEIS_GO_DEV_IMAGE} make run-packer
    displayName: Building VHD
  - script: make info
    displayName: Copying resource to Classic Storage Account

