trigger: none

# steps: 
# - create an VHD in Packer to normal storage account
# - copy from Packer storage account to classic storage account using AzCopy
# - generate SAS link from azure CLI
# - POST a new SKU to azure marketplace

phases:
- phase: build_vhd
  queue: Hosted Linux Preview
  steps:
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/acs-engine \
      -w /go/src/github.com/Azure/acs-engine \
      -e CLIENT_ID=${CLIENT_ID} \
      -e CLIENT_SECRET="$(CLIENT_SECRET)" \
      -e TENANT_ID=${TENANT_ID} \
      -e AZURE_VM_SIZE=${AZURE_VM_SIZE} \
      -e AZURE_RESOURCE_GROUP_NAME=${AZURE_RESOURCE_GROUP_NAME} \
      -e AZURE_LOCATION=${AZURE_LOCATION} \
      ${DEIS_GO_DEV_IMAGE} make run-packer
    displayName: Building VHD
  - script: |
      OS_DISK_SAS="$(cat packer-output | grep "OSDiskUriReadOnlySas:" | cut -d " " -f 2)" && \
      VHD_NAME="$(echo $OS_DISK_SAS | cut -d "/" -f 8 | cut -d "?" -f 1)" && \
      printf "COPY ME ----> ${CLASSIC_BLOB}/${VHD_NAME}?" | tee -a vhd-sas && \
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/acs-engine \
      -w /go/src/github.com/Azure/acs-engine \
      -e CLIENT_ID=${CLIENT_ID} \
      -e CLIENT_SECRET="$(CLIENT_SECRET)" \
      -e TENANT_ID=${TENANT_ID} \
      -e CLASSIC_BLOB=${CLASSIC_BLOB} \
      -e CLASSIC_SAS_TOKEN="$(SAS_TOKEN)" \
      -e OS_DISK_SAS=${OS_DISK_SAS} \
      -e VHD_NAME=${VHD_NAME} \
      ${DEIS_GO_DEV_IMAGE} make az-copy
    displayName: Copying resource to Classic Storage Account
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/acs-engine \
      -w /go/src/github.com/Azure/acs-engine \
      -e CLIENT_ID=${CLIENT_ID} \
      -e CLIENT_SECRET="$(CLIENT_SECRET)" \
      -e TENANT_ID=${TENANT_ID} \
      -e CLASSIC_SA_CONNECTION_STRING="$(CLASSIC_SA_CONNECTION_STRING)" \
      -e START_DATE=${START_DATE} \
      -e EXPIRY_DATE=${EXPIRY_DATE} \
      ${DEIS_GO_DEV_IMAGE} make generate-sas
    displayName: Getting Shared Access Signature URI
