    "{{.Name}}Count": {
      "allowedValues": [
        1, 
        2, 
        3, 
        4, 
        5, 
        6, 
        7, 
        8, 
        9, 
        10, 
        11, 
        12, 
        13, 
        14, 
        15, 
        16, 
        17, 
        18, 
        19, 
        20, 
        21, 
        22, 
        23, 
        24, 
        25, 
        26, 
        27, 
        28, 
        29, 
        30, 
        31, 
        32, 
        33, 
        34, 
        35, 
        36, 
        37, 
        38, 
        39, 
        40, 
        41, 
        42, 
        43, 
        44, 
        45, 
        46, 
        47, 
        48, 
        49, 
        50, 
        51, 
        52, 
        53, 
        54, 
        55, 
        56, 
        57, 
        58, 
        59, 
        60, 
        61, 
        62, 
        63, 
        64, 
        65, 
        66, 
        67, 
        68, 
        69, 
        70, 
        71, 
        72, 
        73, 
        74, 
        75, 
        76, 
        77, 
        78, 
        79, 
        80, 
        81, 
        82, 
        83, 
        84, 
        85, 
        86, 
        87, 
        88, 
        89, 
        90, 
        91, 
        92, 
        93, 
        94, 
        95, 
        96, 
        97, 
        98, 
        99, 
        100
      ], 
      "defaultValue": {{.Count}}, 
      "metadata": {
        "description": "The number of Mesos agents for the cluster.  This value can be from 1 to 100"
      }, 
      "type": "int"
    },
    "{{.Name}}VMSize": {
      "allowedValues": [
        "Standard_A0", 
        "Standard_A1", 
        "Standard_A2", 
        "Standard_A3", 
        "Standard_A4", 
        "Standard_A5", 
        "Standard_A6", 
        "Standard_A7", 
        "Standard_A8", 
        "Standard_A9", 
        "Standard_A10", 
        "Standard_A11", 
        "Standard_D1", 
        "Standard_D2", 
        "Standard_D3", 
        "Standard_D4", 
        "Standard_D11", 
        "Standard_D12", 
        "Standard_D13", 
        "Standard_D14", 
        "Standard_D1_v2", 
        "Standard_D2_v2", 
        "Standard_D3_v2", 
        "Standard_D4_v2", 
        "Standard_D5_v2", 
        "Standard_D11_v2", 
        "Standard_D12_v2", 
        "Standard_D13_v2", 
        "Standard_D14_v2", 
        "Standard_G1", 
        "Standard_G2", 
        "Standard_G3", 
        "Standard_G4", 
        "Standard_G5", 
        "Standard_DS1", 
        "Standard_DS2", 
        "Standard_DS3", 
        "Standard_DS4", 
        "Standard_DS11", 
        "Standard_DS12", 
        "Standard_DS13", 
        "Standard_DS14", 
        "Standard_GS1", 
        "Standard_GS2", 
        "Standard_GS3", 
        "Standard_GS4", 
        "Standard_GS5"
      ], 
      "defaultValue": "{{.VMSize}}", 
      "metadata": {
        "description": "The size of the Virtual Machine."
      }, 
      "type": "string"
    },
{{if .IsCustomVNET}}
    "{{.Name}}VnetSubnetID": {
      "defaultValue": "{{.VnetSubnetID}}",
      "metadata": {
        "description": "Sets the vnet subnet of agent pool '{{.Name}}'."
      }, 
      "type": "string"
    }
{{else}}
    "{{.Name}}Subnet": {
      "defaultValue": "{{.GetSubnet}}",
      "metadata": {
        "description": "Sets the subnet of agent pool '{{.Name}}'."
      }, 
      "type": "string"
    }
{{end}}
{{if IsPublic .Ports}}
  ,"{{.Name}}EndpointDNSNamePrefix": {
      "defaultValue": "{{.DNSPrefix}}",
      "metadata": {
        "description": "Sets the Domain name label for the agent pool IP Address.  The concatenation of the domain name label and the regional DNS zone make up the fully qualified domain name associated with the public IP address."
      }, 
      "type": "string"
    }
{{end}} 