    "maxVMsPerPool": 100,
    "maxVMsPerStorageAccount": 20,
    "maxStorageAccountsPerAgent": "[div(variables('maxVMsPerPool'),variables('maxVMsPerStorageAccount'))]",
    "apiServerCertificate": "[parameters('apiServerCertificate')]",
    "apiServerPrivateKey": "[parameters('apiServerPrivateKey')]",
    "caCertificate": "[parameters('caCertificate')]",
    "clientCertificate": "[parameters('clientCertificate')]",
    "clientPrivateKey": "[parameters('clientPrivateKey')]",
    "kubeConfigCertificate": "[parameters('kubeConfigCertificate')]",
    "kubeConfigPrivateKey": "[parameters('kubeConfigPrivateKey')]",
    "kubernetesHyperkubeSpec": "[parameters('kubernetesHyperkubeSpec')]",
    "servicePrincipalClientId": "[parameters('servicePrincipalClientId')]",
    "servicePrincipalClientSecret": "[parameters('servicePrincipalClientSecret')]",
    "username": "[parameters('linuxAdminUsername')]",
{{if AnyAgentHasDisks}}
    "dataStorageAccountPrefixSeed": 97,
{{end}}
    "masterFqdnPrefix": "[parameters('masterEndpointDNSNamePrefix')]",
    "masterPrivateIp": "[parameters('firstConsecutiveStaticIP')]",
    "masterVMSize": "[parameters('masterVMSize')]",
    "sshPublicKeyData": "[parameters('sshRSAPublicKey')]",
    "masterCount": {{.MasterProfile.Count}},   
    "apiVersionDefault": "2016-03-30",
    "apiVersionStorage": "2015-06-15",
    "kubeDnsServiceIp": "10.0.0.10", 
    "kubeServiceCidr": "10.0.0.0/16", 
    "location": "[resourceGroup().location]", 
    "masterAvailabilitySet": "master-availabilityset",
    "nsgName": "[concat(variables('masterVMNamePrefix'), 'nsg')]",
    "masterNSGID": "[resourceId('Microsoft.Network/networkSecurityGroups',variables('nsgName'))]",
    "masterPublicIPAddressName": "[concat(variables('orchestratorName'), '-master-ip-', variables('masterFqdnPrefix'), '-', variables('nameSuffix'))]",
    "storageAccountBaseName": "[uniqueString(concat(variables('masterFqdnPrefix'),resourceGroup().location, variables('orchestratorName')))]",
    "masterStorageAccountName": "[concat(variables('storageAccountBaseName'), 'mstr0')]",
    "nameSuffix": "{{GetUniqueNameSuffix}}", 
    "orchestratorName": "k8s",  
    "osImageOffer": "UbuntuServer", 
    "osImagePublisher": "Canonical", 
    "osImageSKU": "16.04.0-LTS", 
    "osImageVersion": "16.04.201606270",
    "resourceGroup": "[resourceGroup().name]", 
    "routeTableName": "[concat(variables('masterVMNamePrefix'),'-routetable')]",
    "sshNatPorts": [22,2201,2202,2203,2204],
    "sshKeyPath": "[concat('/home/',variables('username'),'/.ssh/authorized_keys')]", 
    "storageAccountBaseName": "[uniqueString(concat(variables('masterFqdnPrefix'),resourceGroup().location))]", 
    "storageAccountPrefixes": [
      "0", 
      "6", 
      "c", 
      "i", 
      "o", 
      "u", 
      "1", 
      "7", 
      "d", 
      "j", 
      "p", 
      "v", 
      "2", 
      "8", 
      "e", 
      "k", 
      "q", 
      "w", 
      "3", 
      "9", 
      "f", 
      "l", 
      "r", 
      "x", 
      "4", 
      "a", 
      "g", 
      "m", 
      "s", 
      "y", 
      "5", 
      "b", 
      "h", 
      "n", 
      "t", 
      "z"
    ], 
    "storageAccountPrefixesCount": "[length(variables('storageAccountPrefixes'))]",
    "vmsPerStorageAccount": 20, 
{{if .MasterProfile.IsCustomVNET}}
    "masterVnetSubnetID": "[parameters('masterVnetSubnetID')]",
{{else}}
    "subnetCidr": "[parameters('masterSubnet')]",
    "subnetName": "[concat(variables('orchestratorName'), '-masterSubnet')]",
    "subnetRef": "[concat(variables('virtualNetworkNameRef'),'/subnets/',variables('subnetName'))]",
    "vnetID": "[resourceId('Microsoft.Network/virtualNetworks',variables('virtualNetworkName'))]",
    "virtualNetworkName": "[concat(variables('orchestratorName'), '-vnet-', variables('nameSuffix'))]",
    "virtualNetworkNameRef": "[resourceId('Microsoft.Network/virtualNetworks',variables('virtualNetworkName'))]", 
{{end}}
    "masterLbID": "[resourceId('Microsoft.Network/loadBalancers',variables('masterLbName'))]", 
    "masterLbIPConfigID": "[concat(variables('masterLbID'),'/frontendIPConfigurations/', variables('masterLbIPConfigName'))]", 
    "masterLbIPConfigName": "[concat(variables('orchestratorName'), '-master-lbFrontEnd-', variables('nameSuffix'))]",
    "masterLbName": "[concat(variables('orchestratorName'), '-master-lb-', variables('nameSuffix'))]",
    "masterLbBackendPoolName": "[concat(variables('orchestratorName'), '-master-pool-', variables('nameSuffix'))]",
    "masterFirstAddrComment": "these MasterFirstAddrComment are used to place multiple masters consecutively in the address space",
    "masterFirstAddrOctets": "[split(parameters('firstConsecutiveStaticIP'),'.')]",
    "masterFirstAddrOctet4": "[variables('masterFirstAddrOctets')[3]]",
    "masterFirstAddrPrefix": "[concat(variables('masterFirstAddrOctets')[0],'.',variables('masterFirstAddrOctets')[1],'.',variables('masterFirstAddrOctets')[2],'.')]",
    "masterVMNamePrefix": "[concat(variables('orchestratorName'), '-master-', variables('nameSuffix'), '-')]",
    "subscriptionId": "[subscription().subscriptionId]",
    "tenantId": "[subscription().tenantId]", 
    "vnetCidr": "10.0.0.0/8"

    
 