    "apiserverCertificate": "[parameters('apiserverCertificate')]",
    "apiserverPrivateKey": "[parameters('apiserverPrivateKey')]",
    "caCertificate": "[parameters('caCertificate')]",
    "clientCertificate": "[parameters('clientCertificate')]",
    "clientPrivateKey": "[parameters('clientPrivateKey')]",
    "kubernetesHyperkubeSpec": "[parameters('kubernetesHyperkubeSpec')]",
    "servicePrincipalClientId": "[parameters('servicePrincipalClientId')]",
    "servicePrincipalClientSecret": "[parameters('servicePrincipalClientSecret')]",
    "username": "[parameters('linuxAdminUsername')]",
    "masterFqdnPrefix": "[parameters('masterFqdnPrefix')]",
    "masterPrivateIp": "[parameters('firstConsecutiveStaticIP')]",
    "masterSize": "[parameters('masterVMSize')]",
    "sshPublicKeyData": "[parameters('sshRSAPublicKey')]",
       
    "apiVersionDefault": "2016-03-30",
    "apiVersionStorage": "2015-06-15",
    "kubeDnsServiceIp": "10.3.0.10", 
    "kubeServiceCidr": "10.3.0.0/16", 
    "location": "[resourceGroup().location]", 
    "masterAvailabilitySet": "master-availabilityset",
    "nsgName": "[concat(variables('masterFqdnPrefix'), '-nsg')]",
    "masterPublicIPAddressName": "[concat(variables('orchestratorName'), '-master-ip-', variables('masterFqdnPrefix'), '-', variables('nameSuffix'))]",
    "storageAccountBaseName": "[uniqueString(concat(variables('masterFqdnPrefix'),resourceGroup().location, variables('orchestratorName')))]",
    "masterStorageAccountName": "[concat(variables('storageAccountBaseName'), 'mstr0')]",
    "nameSuffix": "{{GetUniqueNameSuffix}}", 
    "orchestratorName": "k8s",  
    "osImageOffer": "UbuntuServer", 
    "osImagePublisher": "Canonical", 
    "osImageSKU": "16.04.0-LTS", 
    "osImageVersion": "16.04.201606270",
    "resourceGroup": "[resourceGroup().name]", 
    "routeTableName": "[variables('masterFqdnPrefix')]",
    "singleQuote": "'", 
    "sshKeyPath": "[concat('/home/',variables('username'),'/.ssh/authorized_keys')]", 
    "storageAccountBaseName": "[concat(uniqueString(concat(variables('masterFqdnPrefix'),resourceGroup().location)))]", 
    "storageAccountPrefixes": [
      "0", 
      "6", 
      "c", 
      "i", 
      "o", 
      "u", 
      "1", 
      "7", 
      "d", 
      "j", 
      "p", 
      "v", 
      "2", 
      "8", 
      "e", 
      "k", 
      "q", 
      "w", 
      "3", 
      "9", 
      "f", 
      "l", 
      "r", 
      "x", 
      "4", 
      "a", 
      "g", 
      "m", 
      "s", 
      "y", 
      "5", 
      "b", 
      "h", 
      "n", 
      "t", 
      "z"
    ], 
    "storageAccountPrefixesCount": "[length(variables('storageAccountPrefixes'))]",
    "vmsPerStorageAccount": 20, 

    "subnetCidr": "10.0.0.0/16", 
    "subnetName": "[concat(variables('masterFqdnPrefix'), '-subnet')]", 
    "subnetRef": "[concat(variables('vnetRef'),'/subnets/',variables('subnetName'))]", 
    "subscriptionId": "[subscription().subscriptionId]",
    "tenantId": "[subscription().tenantId]", 
    "vmNamePrefix": "[concat(variables('masterFqdnPrefix'), '-vm-')]", 
    "vnetCidr": "10.0.0.0/8", 
    "vnetName": "[concat(variables('masterFqdnPrefix'), '-vnet')]", 
    "vnetRef": "[resourceId('Microsoft.Network/virtualNetworks',variables('vnetName'))]"

    
 