---
localmaster:
  hosts:
    localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2

    oreg_url_master: 'TEMPIMAGEBASE-${component}:${version}'

    # The value of TEMPROUTERIP will be substituted during the acs-engine ARM
    # Deployment process with the correct ip address
    openshift_master_default_subdomain: 'TEMPROUTERIP.nip.io'

    # FIXME
    # This should be type=infra, but we have to live with region=infra for now
    # because of legacy reasons
    openshift_router_selector: 'region=infra'
    openshift_deployment_type: 'openshift-enterprise'
    # NOTE: Do not define openshift_hosted_router_replicas so that the task file
    # router.yml inside the openshift_hosted role from openshift-ansible will
    # autopopulate it using the openshift_hosted_router_selector and querying
    # the number of infra nodes

    openshift:
      common:
        config_base: /etc/origin/
