---
localmaster:
  hosts:
    localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2

    oreg_url_master: 'TEMPIMAGEBASE-${component}:${version}'

    # The value of TEMPROUTERIP will be substituted during the acs-engine ARM
    # Deployment process with the correct ip address
    openshift_master_default_subdomain: 'TEMPROUTERIP.nip.io'

    # FIXME
    # This should be type=infra, but we have to live with region=infra for now
    # because of legacy reasons
    openshift_router_selector: 'region=infra'
    openshift_registry_selector: 'region=infra'

    # Set Azure specific data for hosted registry
    openshift_hosted_registry_storage_provider: "azure_blob"
    openshift_hosted_registry_storage_kind: "object"
    openshift_hosted_registry_storage_azure_blob_accountname: 'REGISTRY_STORAGE_AZURE_ACCOUNTNAME'
    openshift_hosted_registry_storage_azure_blob_accountkey: 'REGISTRY_STORAGE_AZURE_ACCOUNTKEY'
    openshift_hosted_registry_storage_azure_blob_container: "registry"
    openshift_hosted_registry_storage_azure_blob_realm: "core.windows.net"

    # FIXME
    #
    # Hard code this for now.
    #
    # Currently the cluster state at deployment time does not have the nodes
    # registered to the master with labels applied and ready to be queried
    # against at the point in time in the deploy that the playbooks run. Also,
    # the router replica count default "falls back" to 1 appropriately where as
    # the registry replica logic does not. There was also discussion about if
    # it's appropriate to do this with replicas == infra nodes because it's
    # perfectly feasible to have an infra node count higher than the desired
    # replicas.
    #
    # Revisit later (possibly a daemonset or $other)
    openshift_hosted_router_replicas: 1
    openshift_hosted_registry_replicas: 1

    openshift_deployment_type: 'openshift-enterprise'

    # NOTE: Do not define openshift_hosted_router_replicas so that the task file
    # router.yml inside the openshift_hosted role from openshift-ansible will
    # autopopulate it using the openshift_hosted_router_selector and querying
    # the number of infra nodes

    openshift:
      common:
        config_base: /etc/origin/
